POST http://localhost:3000/videos
// Com esse comando eu estou avisando pro meu backend que é um arquivo Json
Content-Type: application/json 
// OBS: quando não estou mandando nada no body, não preciso desse meta dado

{
	"title": "NODE DO ZERO",
	"description": "Aprendendo node do zero",
	"duration": 180
}

###

GET http://localhost:3000/videos

###

PUT http://localhost:3000/videos/482e2777-fd9f-42f0-ab09-e543e4e397d2
Content-Type: application/json

{
	"title": "Linux",
	"description": "Aprendendo linux com CursoemVideo",
	"duration": 40
}

###

DELETE http://localhost:3000/videos/f93ad258-9241-4b51-9e9a-7614928dcd59